#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

require __DIR__ . '/config/constants.php';
require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/src/common/Yii.php';
require __DIR__ . '/config/bootstrap.php';

$config = require __DIR__ . '/config/console.php';

$app = new yii\console\Application($config);
$exitCode = $app->run();
